apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Roboshop
  region: us-east-1

managedNodeGroups:
  - name: spot-workers
    desiredCapacity: 2
    minSize: 1
    maxSize: 5
    spot: true
    instanceTypes:
      - c5.large
      - c5a.large
      - c5n.large
      - m5.large
      - m5a.large

#kubectl create cluster -f <file.yaml>